services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: customers_db
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3307:3306"  # Port externe différent pour éviter les conflits
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  customers-service:
    build:
      context: .     # ✅ Garde seulement cette ligne
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/customers_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: isaac
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
