server:
  port: 8080
  #8083

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://book-postgres:5432/book_db
    username: postgres
    password: isaac
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
