book-service:
  build:
    context: ./book-service
  depends_on:
    - mysql
  ports:
    - "8082:8080"
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_db
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: isaac
  networks:
    - app-network
