server:
    port: 8080
    #8085

spring:
    config:
        activate:
            on-profile: default

    data:
        mongodb:
            host: localhost
            port: 27017
            database: loan_db

app:
    book-service:
        host: localhost
        port: 8080
        #8083

    customer-service:
        host: localhost
        port: 8080
        #8081

    employee-service:
        host: localhost
        port: 8080
        #8082
