server:
    port: 8085

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            database: loan_db

app:
    book-service:
        host: localhost
        port: 8083

    customer-service:
        host: localhost
        port: 8081

    employee-service:
        host: localhost
        port: 8082
