@startuml
hide circle
top to bottom direction

!define ENTITY(entityName) class entityName << Entity >>
!define AGGREGATE_ROOT(aggregateRootName) class aggregateRootName << Aggregate Root >>
!define VALUE_OBJECT(valueObjectName) class valueObjectName << Value Object >>
!pragma useVerticalIf on
skinparam dpi 350
skinparam packageStyle rectangle
skinparam rectangle {
    BackgroundColor #f7f4eb
    BorderColor Black
}

' Loan Domain (Aggregator Microservice)
Package "Loan Management (Aggregate Root)" <<Rectangle>> #FFEB3B {
    AGGREGATE_ROOT(Loan) #lightpink {
        loanId: UUID
        loanAmount: Decimal
        loanDate: LocalDate
        dueDate: LocalDate
        returnDate: LocalDate
        status: LoanStatus
    }

    VALUE_OBJECT(LoanIdentifier) #Bisque {
        loanId: UUID
    }

    Loan --> LoanIdentifier


    note right of Loan
        dueDate must be after loanDate \n
        Loan must reference valid book, member, and librarian
    end note
}

' Book Domain
Package "Catalog Management Sub-Domain" <<Rectangle>> #D1C4E9 {
    ENTITY(Book) #lightblue {
        title: String
        author: String
        genre: String
        isbn: String
        price: Double
        publishedDate: String
        copiesAvailable: Integer
    }
    VALUE_OBJECT(BookIdentifier) #Bisque {
        bookId: UUID
    }
    Book --> BookIdentifier
    BookIdentifier <-- Loan

    note right of Book
        isbn must be unique
    end note
}

' Member Domain
Package "Member Management Sub-Domain" <<Rectangle>> #E8F5E9 {
    ENTITY(Member) #lightblue {
        firstName: String
        lastName: String
        email: String
        membershipType: String
        phoneNumbers: List<PhoneNumber>
    }
    VALUE_OBJECT(MemberIdentifier) #Bisque {
        memberId: UUID
    }
    VALUE_OBJECT(MemberAddress) #Bisque {
        street: String
        city: String
        province: String
        country: String
    }
    VALUE_OBJECT(PhoneNumber) #Bisque {
        type: PhoneType
        number: String
    }
    VALUE_OBJECT(PhoneType) #Bisque {
        value: String
    }
    Member --> MemberIdentifier
    Member o--> MemberAddress
    Member o--> PhoneNumber
    PhoneNumber --> PhoneType
    MemberIdentifier <-- Loan

    note right of Member
        first name and last name must be unique
    end note
}

' Staff Domain
Package "Staff Management Sub-Domain" <<Rectangle>> #3399FF {
    ENTITY(Librarian) #lightblue {
        firstName: String
        lastName: String
        email: String
        salary: Decimal
        commissionRate: Double
        department: Department
    }
    VALUE_OBJECT(LibrarianIdentifier) #Bisque {
        librarianId: UUID
    }
    VALUE_OBJECT(Address) #Bisque {
        street: String
        city: String
        province: String
        country: String
        postalCode: String
    }
    VALUE_OBJECT(Department) #Bisque {
        name: String
    }
    Librarian --> LibrarianIdentifier
    Librarian o--> Address
    Librarian --> Department
    LibrarianIdentifier <-- Loan

    note right of Librarian
        email must be unique
    end note
}

@enduml