server:
    port: 8080
    error:
        include-message: always

logging:
    level:
        root: INFO
        com.example: DEBUG

spring:
    config:
        activate:
            on-profile: docker

app:
    employee-service:
        host: employee-service
        port: 8080 #8082 before

    customers-service:
        host: customers-service
        port: 8080 #8081 before

    book-service:
        host: book-service
        port: 8080 #8083 before

    loan-service:
        host: loan-service
        port: 8080 #8085 before
